# Site
name: "XT DEV."
title: "XT DEV."
description: ""
logo: "assets/images/logo-xt.png"
favicon: "assets/images/logo-xt.png"
url: "https://xt-frontend.github.io"
# url: "http://localhost:4000"
baseurl: https://xt-frontend.github.io
# baseurl: ""
google_analytics: "UA-46278016-1"
# disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
comments: true
disqus: "xt-frontend"

# Authors
authors:
  # 강대철
  kangdaecheol:
    name: mcrg012 # 아이디
    display_name: mcrg012 # 실제 노출되는 아이디
    avatar: "assets/images/avatar/kangdaecheol-avatar.jpg" # 아바타 이미지
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: mcrg012@ex-it.co.kr # 이메일
    web: https://www.wowthemes.net # 개인 블로그 url
    description: ""

  # 김규태
  kimgyutae:
    name: uncha
    display_name: uncha
    avatar: "assets/images/avatar/uncha-avatar.jpeg"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: uncha@ex-it.co.kr
    web: https://www.wowthemes.net
    description: ""

  # 도신애
  doshinae:
    name: elin0117
    display_name: elin0117
    avatar: "assets/images/avatar/doshinae-avatar.jpeg"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: elin0117@ex-it.co.kr
    web: https://www.wowthemes.net
    description: ""

  # 김학민
  kimhakmin:
    name: kimhm260
    display_name: kimhm260
    avatar: "assets/images/avatar/kimhakmin-avatar.jpeg"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: kimhm260@ex-it.co.kr
    web: https://www.wowthemes.net
    description: ""

  # 전현정
  jeonhyeonjeong:
    name: jeonhyeonjeong
    display_name: jeonhyeonjeong
    avatar: "assets/images/avatar/jhj.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: jeonhyeonjeong@ex-it.co.kr
    web: https://www.wowthemes.net
    description: ""

  # 박상수
  parksangsu:
    name: pss0728
    display_name: pss0728
    avatar: "assets/images/avatar/parksangsu-avatar.jpeg"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: pss0728@ex-it.co.kr
    web: https://www.wowthemes.net
    description: ""

  # 김유라
  kimyura:
    name: urakim
    display_name: urakim
    avatar: "assets/images/avatar.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: urakim@ex-it.co.kr
    web: https://www.wowthemes.net
    description: ""

  # 송영춘
  songyeoungchun:
    name: songyeoungchun
    display_name: songyeoungchun
    avatar: "assets/images/syc-avatar.png"
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: yy8703@ex-it.co.kr
    web: https://mydevlop.tistory.com/
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jemoji

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
